version: '3.8'
services:
  service-emergency:
    platform: linux/x86_64
    ports:
      - 6061:6061
    image: service-emergency-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "TZ=Europe/Rome"
    container_name: service-emergency
    networks:
      - net_storage

networks:
  net_storage:
    name: net_storage
    external: true